CONTRIBUTING: improvements
nmstate/nmstate pull request #1322
Opened 2020-09-06 16:49 UTC by Razaloc

- Add Code Structure.

 - Add Configure Git.

 - Add How to write a good commit.

 - Add references to Pro Git and the developer guide.

 - Erase reference to commit-template.txt

 - Erase empty file ./libnmstate/README.md

Signed-off-by: Rafael G. Ruiz <llerrak@hotmail.com>

2020-09-07 07:56 UTC, cathay4t requested changes

2020-09-07 07:56 UTC, cathay4t commented on CONTRIBUTING.md
> +`./libnmstate/schemas/` Contains the API.
Can you break this line into smaller parts?

2020-09-07 07:56 UTC, cathay4t commented on CONTRIBUTING.md
> +- `./tests/` - Contains tests for unitary integration, nmstatectl and the API.
- `./tests/` - Contains tests for unit and integration tests.

2020-09-09 13:41 UTC, ffmancera requested changes
I made a comment below. In addition, could you change the commit message to `CONTRIBUTING: add information about git and code structure`.

Other than that, it looks good. Thanks!

2020-09-09 13:41 UTC, ffmancera commented on CONTRIBUTING.md
> +You can check the [developer guide](https://www.nmstate.io/devel/dev_guide.html).
I would prefer "Please check" instead of "You can check".

2020-09-09 14:13 UTC, cathay4t requested changes

2020-09-09 14:13 UTC, cathay4t commented on CONTRIBUTING.md
> +- `./libnmstate/nm/` Contains the support of NetworkManager.
Contains the nmstate NetworkManager plugin, currently for querying network status and applying network states.

2020-09-09 14:13 UTC, cathay4t commented on CONTRIBUTING.md
> +- `./libnmstate/nispor/` Contains tools to comunicate with nispor.
Contains the nmstate nispor plugin, currently for querying kernel network status.

2020-09-09 14:13 UTC, cathay4t commented on CONTRIBUTING.md
> +- `./libnmstate/schemas/` Contains the API.
Contains the API schema file.

2020-09-09 14:13 UTC, cathay4t commented on CONTRIBUTING.md
> +- `./nmstatectl/` - Contains command lines tools.
Contains command lines tools and varlink service.

2020-09-09 17:47 UTC, cathay4t approved these changes
LGTM. Thanks.

2020-09-09 22:28 UTC, merged