inclusive language: deprecate "slaves" from the API
nmstate/nmstate pull request #1330
Opened 2020-09-10 10:12 UTC by ffmancera

* Bond.SLAVES is now deprecated by Bond.PORT

* OVSBridge.Port.LinkAggregation.SLAVES_SUBTREE is now deprecated by
  OVSBridge.Port.LinkAggregation.PORT_SUBTREE

* OVSBridge.Port.LinkAggregation.Slave.NAME is now deprecated by
  OVSBridge.Port.LinkAggregation.Port.NAME

* Team.PORT_SUBTREE is now "port" instead of "ports"

Signed-off-by: Fernando Fernandez Mancera <ffmancera@riseup.net>

2020-09-10 14:01 UTC, cathay4t requested changes

2020-09-10 14:01 UTC, cathay4t commented on libnmstate/schema.py
> +    PORT_SUBTREE = "port"
This is breaking the API. Please do in another PR.

Possible approach for not breaking API as old working yaml will not pass the schema check.

Include both `ports` and `port` in schema.

In `libnmstate/ifaces/team.py`, change the `ports` in desire state to `port` and raise a warnning.

Both `ports` and `port` in desire state should works.

2020-09-10 14:03 UTC, cathay4t commented
Only did partial reviews. Have to manually test whether old API still works.

2020-09-10 14:14 UTC, EdDev commented on libnmstate/schema.py
> +    PORT_SUBTREE = "port"
Deprecation warnings are supposed to be handled by ‘ DEPRECATED_CONSTANTS’, no? Is there another part that breaks?

2020-09-10 16:02 UTC, ffmancera commented on libnmstate/schema.py
> +    PORT_SUBTREE = "port"
The problem here is that DEPRECATED_CONSTANTS mechanism works for removing/replacing constants. In this case, we are NOT modifying the constant but its value so it's different. IMO, @cathay4t proposed mechanism should work. I will try it out in another PR.

2020-09-10 16:03 UTC, ffmancera commented
> Only did partial reviews. Have to manually test whether old API still works.

Will test it manually too. I think it should work as the deprecation test is passing.

2020-09-11 08:10 UTC, ffmancera commented on libnmstate/schema.py
> +    PORT_SUBTREE = "port"
I've removed it from this PR.

2020-09-11 10:13 UTC, ffmancera commented
I've tested this manually, here is the output:

```
Python 3.6.8 (default, Apr 16 2020, 01:36:27) 
[GCC 8.3.1 20191121 (Red Hat 8.3.1-5)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from libnmstate.schema import Bond
>>> from libnmstate.schema import OVSBridge
>>> Bond.SLAVES
sys:1: FutureWarning: Using 'Bond.SLAVES' is deprecated, use 'Bond.PORT' instead.
'port'
>>> OVSBridge.Port.LinkAggregation.SLAVES_SUBTREE
sys:1: FutureWarning: Using 'LinkAggregation.SLAVES_SUBTREE' is deprecated, use 'OVSBridge.Port.LinkAggregation.PORT_SUBTREE' instead.
'port'
>>> OVSBridge.Port.LinkAggregation.Slave.NAME
sys:1: FutureWarning: Using 'LinkAggregation.Slave' is deprecated, use 'OVSBridge.Port.LinkAggregation.Port' instead.
'name'
```

2020-09-18 07:29 UTC, cathay4t requested changes
When yml file still using old `slave` term, the apply will fail, this is not acceptable.

We should still support old term of `slave` regardless user use it as constant or hard-coded string.

2020-09-22 11:59 UTC, ffmancera commented
> When yml file still using old `slave` term, the apply will fail, this is not acceptable.
> 
> We should still support old term of `slave` regardless user use it as constant or hard-coded string.

I've fixed this. Thanks!

2020-09-23 13:42 UTC, cathay4t requested changes
The `schemas/operational-state.yaml` is not updated.
And it should allows both old and new terms.

2020-09-23 13:42 UTC, cathay4t commented on libnmstate/ifaces/bond.py
> +        lag_info = self.raw.get(Bond.CONFIG_SUBTREE)
Use `bond_cfg` or `bond_info` please, as there is no other code in this file using term of `lag`.

2020-09-23 14:51 UTC, ffmancera commented on libnmstate/ifaces/bond.py
> +        lag_info = self.raw.get(Bond.CONFIG_SUBTREE)
Done, thanks!

2020-09-23 14:54 UTC, ffmancera commented
> The `schemas/operational-state.yaml` is not updated.
> And it should allows both old and new terms.

Done, thank you!

2020-09-24 14:15 UTC, cathay4t approved these changes
LGTM. Thanks.

2020-09-24 14:47 UTC, merged