vlan: Raise exception if base iface is infiniband.
nmstate/nmstate pull request #1377
Opened 2020-10-10 19:02 UTC by adwait-thattey

Adds a validator that raises NmstateValueError if
base iface of Vlan/Vxlan is IB interface

Tests are also added

Fixes #1353

Signed-off-by: Adwait Thattey <coderdude1999@gmail.com>

2020-10-12 03:18 UTC, cathay4t requested changes
Looks really great ~~for a new commer~~.
Just a trivial change required.

Thanks.

2020-10-12 03:18 UTC, cathay4t commented on libnmstate/ifaces/ifaces.py
> +                base_iface = self._ifaces.get(iface.parent)
Previous validation functions has confirmed the existence of parent interface. Just use `self._ifaces[iface.parent]`.

2020-10-12 08:32 UTC, adwait-thattey commented
@cathay4t I have made the changes.
Thank You

2020-10-12 16:32 UTC, cathay4t approved these changes

2020-10-12 16:35 UTC, cathay4t commented
@adwait-thattey Thanks for the patch. Can you do a rebase?

2020-10-12 18:25 UTC, adwait-thattey commented
@cathay4t rebased.
Thanks

2020-10-13 04:07 UTC, adwait-thattey commented
@cathay4t Rebased again

2020-10-13 05:24 UTC, merged

2020-10-13 05:24 UTC, cathay4t commented
Merged. Thanks for your help.