.github: enable github actions using ubuntu
nmstate/nmstate pull request #1452
Opened 2020-12-24 18:08 UTC by ffmancera

Signed-off-by: Fernando Fernandez Mancera <ffmancera@riseup.net>

2020-12-24 18:13 UTC, ffmancera commented
@cathay4t Not sure if this is going to work well but the action will not enabled until this commit is merged. If there is any issue I will disable it.

2020-12-29 06:49 UTC, cathay4t approved these changes

2020-12-29 06:51 UTC, cathay4t requested changes
the yamllint failed the ci. please fix. Thanks!

2021-01-04 05:57 UTC, cathay4t commented
I have fixed the yamlint issue.

Our travis CI credit is running out. Merging it and will fix later.

2021-01-04 05:57 UTC, merged