bond: add support to vlan+srcmac tx hashing option
nmstate/nmstate pull request #1495
Opened 2021-01-25 14:58 UTC by ffmancera

The new vlan+srcmac tx hashing option is now available at kernel
upstream. Nmstate is now supporting it.

Ref: https://git.kernel.org/pub/scm/linux/kernel/git/netdev/net-next.git/commit/?id=7b8fc0103bb51d1d3e1fb5fd67958612e709f883

Signed-off-by: Fernando Fernandez Mancera <ffmancera@riseup.net>

2021-01-25 15:07 UTC, cathay4t commented
Let's wait NetworkManager master branch has the code actually support this.

2021-02-01 23:00 UTC, ffmancera commented
@cathay4t Nmstate is getting random errors from NM master. It seems they saw something similar on their CI. I've reported this in the following BZ and NM team is working on it. 

https://bugzilla.redhat.com/show_bug.cgi?id=1923248

The error is not related to this change. IMO, we should not block our CI on this.

2021-02-02 09:36 UTC, cathay4t requested changes
Please change the CI test case to use `nmcli -g bond.options c show bond99` to verify the options saved into NM profile.

2021-02-08 11:11 UTC, ffmancera commented
> Please change the CI test case to use `nmcli -g bond.options c show bond99` to verify the options saved into NM profile.

Done, thank you!

2021-02-08 11:57 UTC, cathay4t approved these changes
LGTM. Thanks.

2021-02-08 12:26 UTC, merged