route: workaround for removing IPv6 default gateway
nmstate/nmstate pull request #1509
Opened 2021-02-09 12:42 UTC by ffmancera

Due to NM bug [1], Nmstate is not removing IPv6 default gateway. In
order to workaround this, Nmstate is deactivating first the interface if
an IPv6 route has been removed.

Integration test added.

[1] https://bugzilla.redhat.com/1837254

Signed-off-by: Fernando Fernandez Mancera <ffmancera@riseup.net>

2021-02-09 13:40 UTC, cathay4t requested changes
The test case still passes without the fix in libnmstate.

2021-02-10 10:57 UTC, ffmancera commented
#1510

2021-02-10 11:30 UTC, ffmancera commented
> The test case still passes without the fix in libnmstate.

Done, fixed!

2021-02-10 14:17 UTC, cathay4t approved these changes
LGTM. Thanks.

2021-02-10 14:17 UTC, merged