tests, integ: extend accept-all-mac-addresses testing
nmstate/nmstate pull request #1590
Opened 2021-05-12 14:43 UTC by ffmancera

In NetworkManager `accept-all-mac-addresses` works in different ways
for virtual interfaces. These tests is making sure we are covering the
feature in the virtual interfaces too.

Signed-off-by: Fernando Fernandez Mancera <ffmancera@riseup.net>

2021-05-13 13:11 UTC, cathay4t requested changes
All the test case are sharing the same name. Can we somehow differentiate them?

2021-05-14 08:51 UTC, ffmancera commented
> All the test case are sharing the same name. Can we somehow differentiate them?

Done, I've added the interface type to the test name. Thank you!

2021-05-14 10:20 UTC, cathay4t submitted a review, later dismissed

2021-05-23 00:39 UTC, cathay4t approved these changes

2021-05-24 04:33 UTC, merged