team: Drop the support of team interfaces
nmstate/nmstate pull request #1649
Opened 2021-06-22 14:01 UTC by ffmancera

2021-06-23 08:55 UTC, cathay4t requested changes

2021-06-23 08:55 UTC, cathay4t commented on libnmstate/validator.py
> +        ):
This lines should be also removed.

2021-06-25 06:37 UTC, ffmancera commented on libnmstate/validator.py
> +        ):
Thanks! Done

2021-06-25 07:59 UTC, cathay4t approved these changes

2021-06-25 08:12 UTC, merged