ovs, dpdk: add support to rx-queue parameter
nmstate/nmstate pull request #1899
Opened 2022-05-17 06:31 UTC by ffmancera

```
---
interfaces:
  - name: ovs-br0
    type: ovs-bridge
    state: up
    bridge:
      options:
        datapath: netdev
      port:
        - name: ovs0
  - name: ovs0
    type: ovs-interface
    state: up
    dpdk:
      devargs: "000:18:00.2"
      rx-queue: 1000
```

Signed-off-by: Fernando Fernandez Mancera <ffmancera@riseup.net>

2022-05-17 08:38 UTC, cathay4t approved these changes
The code looks good to me. Please wait more time for me to try on real hardware.

2022-05-17 15:59 UTC, cathay4t requested changes
In real server, you get verification error: 

NmstateError: VerificationError: Verification failure: ovs0.interface.dpdk desire '{"devargs":"0000:af:00.0","rx-queue":100}', current 'null'

This is caused you use `n_rxq` when parsing dbus.

2022-05-17 15:59 UTC, cathay4t commented on rust/src/lib/nm/nm_dbus/connection/ovs.rs
> +            n_rxq: _from_map!(v, "n_rxq", u32::try_from)?,
Should be `n-rxq` in the dbus content.

This is output of on real server:

```
[root@dell-per740-10 rust]# qdbus-qt5 --literal  --system \
    org.freedesktop.NetworkManager \
    /org/freedesktop/NetworkManager/Settings/11 \
    org.freedesktop.NetworkManager.Settings.Connection.GetSettings

[Argument: a{sa{sv}} {"connection" = [Argument: a{sv} {"id" =
[Variant(QString): "ovs0-if"], "interface-name" = [Variant(QString): "ovs0"],
"master" = [Variant(QString): "a33e1595-5704-45d3-b357-4f57b19edade"],
"permissions" = [Variant(QStringList): {}], "slave-type" = [Variant(QString):
"ovs-port"], "timestamp" = [Variant(qulonglong): 1652802726], "type" =
[Variant(QString): "ovs-interface"], "uuid" = [Variant(QString):
"8f29fb1a-3a44-4008-8117-7a5a13fb9033"]}], "ovs-dpdk" = [Argument: a{sv}
{"devargs" = [Variant(QString): "0000:af:00.0"], "n-rxq" = [Variant(uint):
100]}], "ovs-interface" = [Argument: a{sv} {"type" = [Variant(QString):
"dpdk"]}], "ipv4" = [Argument: a{sv} {"address-data" = [Variant: [Argument:
aa{sv} {}]], "addresses" = [Variant: [Argument: aau {}]], "dns-search" =
[Variant(QStringList): {}], "method" = [Variant(QString): "disabled"],
"route-data" = [Variant: [Argument: aa{sv} {}]], "routes" = [Variant:
[Argument: aau {}]]}], "ipv6" = [Argument: a{sv} {"address-data" = [Variant:
[Argument: aa{sv} {}]], "addresses" = [Variant: [Argument: a(ayuay) {}]],
"dns-search" = [Variant(QStringList): {}], "method" = [Variant(QString):
"disabled"], "route-data" = [Variant: [Argument: aa{sv} {}]], "routes" =
[Variant: [Argument: a(ayuayu) {}]]}], "proxy" = [Argument: a{sv} {}]}]
```

2022-05-18 08:21 UTC, ffmancera commented on rust/src/lib/nm/nm_dbus/connection/ovs.rs
> +            n_rxq: _from_map!(v, "n_rxq", u32::try_from)?,
Fixed, thank you!

2022-05-18 09:13 UTC, cathay4t commented
Got failure `E       fixture 'setup_ovs_dpdk' not found` when running pytest tests.

2022-05-18 12:20 UTC, ffmancera commented
> Got failure `E fixture 'setup_ovs_dpdk' not found` when running pytest tests.

Please, review it again. Thanks.

2022-05-18 15:23 UTC, cathay4t approved these changes

2022-05-18 15:23 UTC, cathay4t commented
The CI failure is because NM fixed a problem in their main branch.

2022-05-18 15:23 UTC, merged