rust/clib: build both cdylib and staticlib
nmstate/nmstate pull request #1937
Opened 2022-06-14 15:17 UTC by celebdor

For applications wishing to embed libnmstate without having to
distribute all its dependencies, it is useful to build the static
library alongside the dynamic one.

2022-06-16 02:04 UTC, cathay4t commented
@celebdor Please sign your git commit with `--signoff` argument.

2022-06-20 08:35 UTC, cathay4t requested changes
Please sign your git commit with --signoff argument.

2022-06-21 13:05 UTC, cathay4t approved these changes

2022-06-21 13:25 UTC, merged

2022-06-21 16:07 UTC, celebdor commented
Thanks!