[nmstate-1.2] ROUTE_RULE: Fixes issue #2235
nmstate/nmstate pull request #2294
Opened 2023-03-24 11:40 UTC by adilGhaffarDev

This PR fixes issue #2235 
Issue root cause: for applying route rules, nmstate creates interface profiles in the metadata. All route-rules with a particular table id are added to an interface profile. This interface is identified by matching route-table id in the route rules to the route-table id in the routes. When it finds a match in the list of routes, the corresponding next-hop-interface is selected. But it doesn't verify if ipv4/ipv6 is enabled on that interface and the list of rules may have both ipv6 and ipv4 rules. In case, ipv4/ipv6 is not enabled on the interface and the rules list has ipv4/ipv6 rules, it's not applied. And nmstate apply eventually fails with desired state not applied error.  
Proposed fix un this PR: When nmstate identifies an interface based on route-table id matching, add an additional check to verify if the corresponding IP family (ipv4 or ipv6) is enabled on the interface identified. To achieve this, input rules are segregated into 2 sets of ipv6 and ipv4 rules. Apply the same logic of identifying the interface for these 2 sets separately by passing the corresponding IP family. So, for ipv4 rules, an interface with ipv4 enabled is always returned. Same for ipv6 rules as well. 

2023-03-26 13:15 UTC, cathay4t commented
@adilGhaffarDev Please fix the CI and all add test case proving the problem you are solving.

2023-03-27 14:17 UTC, adilGhaffarDev commented
> @adilGhaffarDev Please fix the CI and all add test case proving the problem you are solving.

I am fixing the issue and also adding tests. I have a question, I want to run the lint test locally(./automation/run-tests.sh --test-type lint) but I am getting the following error:
`Trying to pull docker.io/nmstate/fedora-nmstate-dev:latest...
Error: initializing source docker://nmstate/fedora-nmstate-dev:latest: reading manifest latest in docker.io/nmstate/fedora-nmstate-dev: errors:
denied: requested access to the resource is denied
unauthorized: authentication required`

Any idea how can fix this?

2023-03-28 08:17 UTC, cathay4t commented
> 

`./automation/run-tests.sh --test-type lint --el8` might work.

Our default option of run-tests is outdated. :(

2023-03-28 12:36 UTC, adilGhaffarDev commented
> `./automation/run-tests.sh --test-type lint --el8` might work.

this works on the base branch but on nmstate-1.2 it is failing.

2023-03-29 00:55 UTC, cathay4t commented
> > `./automation/run-tests.sh --test-type lint --el8` might work.
> 
> this works on the base branch but on nmstate-1.2 it is failing.

OK. Let me sort it through.

2023-03-29 12:44 UTC, cathay4t commented
Fixed. Please rebase and try again.

2023-03-30 08:10 UTC, adilGhaffarDev commented
> Fixed. Please rebase and try again.

I am still getting following error:
`+ podman exec -t -i db8075f61f81c647148de1d053de88595401a6a66b09e55c1e5f4231f49b5809 /bin/bash -c 'cd /workspace/nmstate && echo '\''/exported-artifacts/core.%h.%e.%t'\'' >         /proc/sys/kernel/core_pattern'
/bin/bash: /proc/sys/kernel/core_pattern: Permission denied
`

2023-04-10 13:01 UTC, cathay4t commented
Please use `sudo ./automation/run-tests.sh --test-type lint --el8`.

If you can also explain the problem with reproducer, maybe I can fix the nmstate 1.4 branch also.

2023-04-19 00:12 UTC, adilGhaffarDev commented
> Please use `sudo ./automation/run-tests.sh --test-type lint --el8`.
> 
> If you can also explain the problem with reproducer, maybe I can fix the nmstate 1.4 branch also.

thank you, this time it worked fine. I have added some test that you can check, they will explain the problem bit more. Let me know if you have any questions. 

Also I want to know can we have this fix also in latest release and main branch too? Code base is switched to Rust so I was having bit difficulty in finding where to add this fix, if you can point in the right direction, I can add this in main branch too.

2023-04-21 07:48 UTC, adilGhaffarDev commented
@cathay4t can you kindly check this.

2023-05-02 10:54 UTC, adilGhaffarDev commented
@ffmancera @cathay4t kindly check this pr

2023-05-08 08:23 UTC, cathay4t commented
Sorry for the late reply, I will review it today and also work on the fix in 1.4 branch and main branch.

2023-05-08 08:48 UTC, cathay4t commented
@adilGhaffarDev I have read the code and guessed out the real user facing problem, are you expecting nmstate to support use case like below?

```yml
---
routes:
  config:
  - destination: 192.168.2.0/24
    metric: 108
    next-hop-address: 192.168.1.3
    next-hop-interface: eth1
    table-id: 200
  - destination: 2001:db8:a::/64
    metric: 108
    next-hop-address: 2001:db8:1::2
    next-hop-interface: eth2
    table-id: 200
route-rules:
  config:
    - ip-from: 192.168.3.2/32
      route-table: 200
    - ip-from: 2001:db8:b::/64
      route-table: 200
interfaces:
  - name: eth1
    type: ethernet
    state: up
    ipv4:
      enabled: true
      dhcp: false
      address:
      - ip: 192.168.1.1
        prefix-length: 24
  - name: eth2
    type: ethernet
    state: up
    ipv6:
      enabled: true
      dhcp: false
      autoconf: false
      address:
      - ip: 2001:db8:1::1
        prefix-length: 64
````

2023-05-08 08:55 UTC, cathay4t requested changes
* Improve the nested route loop.
 * Use integration test case first, and only use unit test case when certain use case is hard to reproduce in real environment, this helps people to understand what's the real problem you try to fix.

2023-05-08 08:55 UTC, cathay4t commented on libnmstate/route_rule.py
> +                for rule in rules_ipfamily[ip_family]:
These nested `for` loop will be a problem when facing large amount of route rules. Please improve the performance of it.

2023-05-08 09:14 UTC, cathay4t commented
Base branch(rust based) does not have this problem, I have created a pull request adding integration test case for this https://github.com/nmstate/nmstate/pull/2337 

Let me know if I get your use case wrong.

If you have trouble on get 1.2/1.4 patch tidy, I can help also.

2023-05-08 09:34 UTC, adilGhaffarDev commented
> Base branch(rust based) does not have this problem, I have created a pull request adding integration test case for this #2337

Thank you for adding test. I want to ask does last release(2.2.10) have this issue?

2023-05-08 09:35 UTC, adilGhaffarDev commented
> @adilGhaffarDev I have read the code and guessed out the real user facing problem, are you expecting nmstate to support use case like below?

yes this looks ok.

2023-05-15 12:31 UTC, cathay4t commented
> > Base branch(rust based) does not have this problem, I have created a pull request adding integration test case for this #2337
> 
> Thank you for adding test. I want to ask does last release(2.2.10) have this issue?

No, 2.2.10 does not have this issue.

2023-05-19 13:03 UTC, adilGhaffarDev commented on libnmstate/route_rule.py
> +                for rule in rules_ipfamily[ip_family]:
I have optimized it little bit kindly check if it looks ok to you, I am open to suggestions.

2023-05-23 11:48 UTC, adilGhaffarDev commented
@cathay4t I have added the optimization that you asked for and also back-ported the integration test, I am getting failure here:

`    @pytest.fixture(scope="function")
    def eth1_up():
        with ifacelib.iface_up("eth1") as ifstate:
>           yield ifstate`

`    def _iface_for_route_table(
        self, route_state, route_table, ifaces, ip_family
    ):
        for routes in route_state.config_iface_routes.values():
            for route in routes:
                if route.table_id == route_table:
                    if self._verify_ip4_ipv6_enabled(route, ifaces, ip_family):
                        return route.next_hop_interface
    
        for iface in ifaces.values():
            autotable_ipv4 = (
                iface.to_dict()
                .get(Interface.IPV4, {})
                .get(InterfaceIP.AUTO_ROUTE_TABLE_ID)
            )
            autotable_ipv6 = (
                iface.to_dict()
                .get(Interface.IPV6, {})
                .get(InterfaceIP.AUTO_ROUTE_TABLE_ID)
            )
            if autotable_ipv4 == route_table or autotable_ipv6 == route_table:
                return iface.name
    
        raise NmstateValueError(
>           "Failed to find interface to with route table ID "
            f"{route_table} to store route rules"
        )`

With this error: 
`E       libnmstate.error.NmstateValueError: Failed to find interface to with route table ID 99 to store route rules

/usr/lib/python3.6/site-packages/libnmstate/route_rule.py:285: NmstateValueError`

I wanted to ask any idea why I am getting this error? any  suggestions to fix this.

2023-06-09 07:05 UTC, adilGhaffarDev commented
@cathay4t kindly check, its hanging there for quite a long time

2023-06-12 11:43 UTC, cathay4t commented
@adilGhaffarDev Sorry for the long wait. In a trip this week, will try to find time to resolve your issue.

2023-07-03 13:11 UTC, cathay4t commented
The failure is caused by nmstate try to preserve current route rule when deleting eth1 interface configurations.

In main branch, nmstate ignore undesired route rule, hence no failure. In nmstate-1.2 branch, nmstate will try to preserve current route rule which lead to this `NmstateValueError: Failed to find interface to with route table ID 99 to store route rules`  for `ERROR at teardown`.

2023-07-03 13:19 UTC, cathay4t commented
Sorry for the long wait. If you allow me, I will create new PR based on your patch for 1.2 and 1.4 branch.

2023-07-03 14:05 UTC, cathay4t commented
@adilGhaffarDev I have created PR using your name in commit author:

 * nmstate-1.2: https://github.com/nmstate/nmstate/pull/2377
 * nmstate-1.4: https://github.com/nmstate/nmstate/pull/2378

2023-07-19 01:17 UTC, cathay4t commented
Closing as no reply and patch been merged via #2377

2023-07-19 01:17 UTC, closed without merging