Pin nic command2
nmstate/nmstate pull request #2301
Opened 2023-03-30 00:30 UTC by cgwalters

This builds on top of https://github.com/nmstate/nmstate/pull/2299 and https://github.com/nmstate/nmstate/pull/2300/ and adds a new interface:

`nmstatectl pin-nic-names` as well as a corresponding systemd unit `nmstatectl-pin-nic-names.service` that can be enabled.

This is aiming to implement https://github.com/nmstate/nmstate/pull/2299#issuecomment-1488993758

2023-03-30 10:26 UTC, tyll commented
IMHO, this command is not in scope of the nmstatectl tool since Nmstate is about defining a state and applying it.
Therefore, this should be a standalone tool and most likely a systemd generator (this is the term used for software that generates systemd units such as link files), similar to https://www.freedesktop.org/software/systemd/man/systemd-network-generator.service.html except that it does not parse the kernel cmdline but the current network state.

In the past, there also used to be a persistent name support in - see for example https://github.com/lu-zero/udev/blob/master/src/rule_generator/write_net_rules - which created udev rules files and was hooked into udev. This could also be a good reason to keep calling this "persistent names" instead of "pinning names" btw.

2023-03-30 11:24 UTC, lnykryn commented on packaging/nmstate-pin-nic-names.service
> +After=NetworkManager.service
This might be too early; maybe use network-online.target instead?

2023-03-30 11:43 UTC, cgwalters commented
> IMHO, this command is not in scope of the nmstatectl tool 

I think everyone would agree this isn't a perfect fit, but creating a *new* tool implies some overhead.

2023-03-30 11:54 UTC, lnykryn commented
> IMHO, this command is not in scope of the nmstatectl tool since Nmstate is about defining a state and applying it. Therefore, this should be a standalone tool and most likely a systemd generator (this is the term used for software that generates systemd units such as link files), similar to https://www.freedesktop.org/software/systemd/man/systemd-network-generator.service.html except that it does not parse the kernel cmdline but the current network state.

You can't use the generator for this. It runs too early in the boot process and they are not supposed to create anything else besides systemd unit files.

2023-03-30 12:08 UTC, cgwalters commented
We should debate the overall architecture; I mentioned this here https://github.com/nmstate/nmstate/pull/2299#issuecomment-1488993758

One important thing here is all current designs call for running this process *once* (or at least, by default).  We're trying to create something that can assist the admin in creating `.link` files retroactively.

Also at the current time in order to aid bootstrap problems my plan is to run this from a privileged container, not the host.  That's the idea behind having this be runnable from `nmstatectl` directly and not the systemd unit, and also the [--root arg commit](https://github.com/nmstate/nmstate/pull/2301/commits/b11721dba7e0019b52bc9ff874e84ac20e823c03).  

> This could also be a good reason to keep calling this "persistent names" instead of "pinning names" btw.

Yeah, makes sense.

So combining these threads we could split this off as a separate binary not branded nmstate; maybe something boring like `nic-name-persist-helper`.

Also, we could for now make this an opt-in Rust feature.  

Again the thought here is to fast track this as a one-off for OCP rhel8->rhel9 upgrades and it will likely only need to be supported in that context only at least initially.

2023-03-30 14:07 UTC, cgwalters commented
(Added an off-by-default feature and split into a separate module)

2023-03-30 20:18 UTC, cgwalters commented
OK a few more changes here, most crucially switching to skipping interfaces using DHCP; I'm 87.3% sure that persisting them is unnecessary in the OCP context.

I also added a container build of this code pushed at [ghcr.io/cgwalters/nmstate:latest](https://github.com/cgwalters/nmstate/pkgs/container/nmstate).

2023-03-31 19:21 UTC, cgwalters commented
One point @dustymabe raised with the "only static IP address" filtering is that it will break e.g. bonds over DHCP.

2023-03-31 19:31 UTC, cgwalters commented
I was also worried about `ip=` on the kernel cmdline, but Dusty also notes that because of the common coreos workflow of propagating network kargs into NM configs via `coreos-copy-firstboot-network.service` we may mainly be dealing with NM configs.

2023-03-31 19:34 UTC, cgwalters commented
Also chatted about Tang and `ip=` as well as anyone today using `rpm-ostree initramfs-etc --track /etc/NetworkManager/system-connections` - basically if we detect that we'll need to also `rpm-ostree initramfs --track /etc/systemd/network`

2023-03-31 20:26 UTC, dustymabe commented
@cgwalters and I were discussing this topic (note I haven't reviewed the code in this PR so this is just comments on the general problem and the appraoch for a solution).

I wonder if we can generalize the solution to this to not worry about static IP/DHCP or not. Can we just look for nm connections that are of ethernet type that are matched based on an interface name. For all that are we add the `.link` file.

Here's an example (taken from the [FCOS docs](https://docs.fedoraproject.org/en-US/fedora-coreos/sysconfig-network-configuration/#_butane_config_2)):

```


variant: fcos
version: 1.4.0
storage:
  files:
    - path: /etc/NetworkManager/system-connections/bond0.nmconnection
      mode: 0600
      contents:
        inline: |
          [connection]
          id=bond0
          type=bond
          interface-name=bond0
          [bond]
          miimon=100
          mode=active-backup
          [ipv4]
          address1=10.10.10.10/24,10.10.10.1
          dhcp-hostname=myhostname
          dns=8.8.8.8;
          dns-search=
          may-fail=false
          method=manual
    - path: /etc/NetworkManager/system-connections/bond0-slave-ens2.nmconnection
      mode: 0600
      contents:
        inline: |
          [connection]
          id=bond0-slave-ens2
          type=ethernet
          interface-name=ens2
          master=bond0
          slave-type=bond
    - path: /etc/NetworkManager/system-connections/bond0-slave-ens3.nmconnection
      mode: 0600
      contents:
        inline: |
          [connection]
          id=bond0-slave-ens3
          type=ethernet
          interface-name=ens3
          master=bond0
          slave-type=bond
```


In this case we just loop over the connections.. Here's the flow:

- iteration `bond0.nmconnection`
    - is connection.type == ethernet
        - "no" -> continue
- iteration `bond0-slave-ens2.nmconnection`
    - is connection.type == ethernet
        - "yes"
            - is connection.interface-name != ""
                - "yes"
                    - write out `.link` file persisting mac addr with `ens2`
- iteration `bond0-slave-ens3.nmconnection`
    - is connection.type == ethernet
        - "yes"
            - is connection.interface-name != ""
                - "yes"
                    - write out `.link` file persisting mac addr with `ens3`

In this flow we don't have to worry about DHCP or static IP and also ignore any device that isn't a physical NIC.

Would this work? What are the flaws here (I'm sure there are some)?

2023-03-31 20:33 UTC, cgwalters commented
Tentatively, I think matching on the connection information makes sense...it looks like to me we could use the `NmApi::active_connections_get()` API instead/in addition?

2023-04-03 09:41 UTC, cathay4t commented
> Tentatively, I think matching on the connection information makes sense...it looks like to me we could use the `NmApi::active_connections_get()` API instead/in addition?

We try to hide backend detail in the top API. We have `state: ignore` for those interface been marked as `unmanaged` in network manager. So I guess we can just filter `state: up` and `type: ethernet` here.

2023-04-03 21:50 UTC, cgwalters commented
xref https://github.com/openshift/machine-config-operator/pull/3650#issuecomment-1495029713 for skipping some OVS types

2023-04-03 21:54 UTC, cgwalters commented
I provisioned a rhel8 system `c3.small.x86` in Equinix.  One interesting discovery is that they actually set up a bond over two NICs set up by DHCP by default!

```
[root@walters-testing-1 network-scripts]# podman run --privileged -v /:/run/host --net=host --rm -ti ghcr.io/cgwalters/nmstate nmstatectl persist-nic-names --root /run/host --dry-run
[2023-04-03T21:51:01Z INFO  nmstatectl::persist_nic] Skipping interface eno1 as no static IP addressing was found
[2023-04-03T21:51:01Z INFO  nmstatectl::persist_nic] Skipping interface eno2 as no static IP addressing was found
[2023-04-03T21:51:01Z INFO  nmstatectl::persist_nic] Would pin the interface with MAC EA:FE:2B:75:6F:3A to interface name enp0s20f0u5u2c2
[2023-04-03T21:51:01Z INFO  nmstatectl::persist_nic] No changes.

[root@walters-testing-1 network-scripts]# ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: enp0s20f0u5u2c2: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UNKNOWN group default qlen 1000
    link/ether ea:fe:2b:75:6f:3a brd ff:ff:ff:ff:ff:ff
    inet6 fe80::479e:6fd1:a2bb:e0bd/64 scope link noprefixroute 
       valid_lft forever preferred_lft forever
3: eno1: <BROADCAST,MULTICAST,SLAVE,UP,LOWER_UP> mtu 1500 qdisc mq master bond0 state UP group default qlen 1000
    link/ether b4:96:91:84:3c:68 brd ff:ff:ff:ff:ff:ff
    altname enp1s0f0
4: eno2: <BROADCAST,MULTICAST,SLAVE,UP,LOWER_UP> mtu 1500 qdisc mq master bond0 state UP group default qlen 1000
    link/ether b4:96:91:84:3c:68 brd ff:ff:ff:ff:ff:ff permaddr b4:96:91:84:3c:69
    altname enp1s0f1
5: bond0: <BROADCAST,MULTICAST,MASTER,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether b4:96:91:84:3c:68 brd ff:ff:ff:ff:ff:ff
    inet 147.28.149.75/31 scope global noprefixroute bond0
       valid_lft forever preferred_lft forever
    inet 10.65.41.1/31 scope global noprefixroute bond0:0
       valid_lft forever preferred_lft forever
    inet6 2604:1380:4643:c00::1/127 scope global noprefixroute 
       valid_lft forever preferred_lft forever
    inet6 fe80::b696:91ff:fe84:3c68/64 scope link noprefixroute 
       valid_lft forever preferred_lft forever
[root@walters-testing-1 network-scripts]# ls -al /sys/class/net/eno1/device/driver/module
lrwxrwxrwx. 1 root root 0 Apr  3 17:52 /sys/class/net/eno1/device/driver/module -> ../../../../module/i40e
[root@walters-testing-1 network-scripts]# ls -al /sys/class/net/eno2/device/driver/module
lrwxrwxrwx. 1 root root 0 Apr  3 17:52 /sys/class/net/eno2/device/driver/module -> ../../../../module/i40e  
[root@walters-testing-1 network-scripts]# ls -al /sys/class/net/enp0s20f0u5u2c2/device/driver/module
lrwxrwxrwx. 1 root root 0 Apr  3 17:52 /sys/class/net/enp0s20f0u5u2c2/device/driver/module -> ../../../../module/cdc_ether
[root@walters-testing-1 network-scripts]# 
```

Also...there seems to be this virtual/emulated [USB Ethernet](https://en.wikipedia.org/wiki/Ethernet_over_USB) device that we're trying to do DHCP on and not getting a reply.  And this shows another bug - we're apparently trying to persist this NIC just because we didn't *succeed* in DHCP on it.  It's using the default/virtual "Wired connection 1".

2023-04-04 16:42 UTC, cgwalters commented
- Per discussion I dropped the previous code to persist via "difference" and managed by `nmstate.service`
- I've squashed all the commits together
- More s/pin/persist/
- The `persist-nic-names` CLI entrypoint is now hidden

I'd like to change to requiring a special `--i-know-this-is-unstable` CLI argument but that requiries ratcheting with the MCO code.  (Hmm, maybe an env variable instead...)

2023-04-04 16:58 UTC, cgwalters commented on rust/src/cli/Cargo.toml
> +persist_nic = []
I guess now that the CLI option is hidden, we can drop the feature flag?

2023-04-04 16:58 UTC, cgwalters commented on .github/workflows/container.yml
> +name: Create and publish a container image
This is optional, but I found it useful

2023-04-04 18:04 UTC, cgwalters commented
OK we did some testing and actually in OpenShift OVN setups move the primary NIC into the OVS bridge, and we definitely need to pin the NIC name in this case.

2023-04-04 19:06 UTC, cgwalters commented
Changelog:

- We now persist devices that are subordinate (e.g. part of a bond, or the `ovs-system` case for OCP)
- Skip anything that's under `devices/virtual`, which avoids persisting the `genev_sys` generated by OCP

2023-04-06 05:29 UTC, cathay4t commented on .github/workflows/container.yml
> +name: Create and publish a container image
We have https://quay.io/organization/nmstate , how about we place it to quay and autobuild on every merge?

2023-04-06 08:00 UTC, cathay4t requested changes
* Please fix `cargo flippy` warnnings.
 * No need to use `.github/workflows/container.yml`, nmstate has quay repo. I will set it up once this PR merged.

2023-04-06 14:40 UTC, cgwalters commented
OK, did both of those.  Dealing with conditional compilation and unused variables is a bit annoying. 

I also dropped the feature and just made it gate on `query_apply`.

2023-04-10 11:31 UTC, cathay4t approved these changes
This PR looks good to me.
I will use another PR to improve this with a clean up process.

2023-04-10 11:32 UTC, cathay4t commented
I am intend to merge this PR. Do we need more discussion here?

2023-04-10 12:00 UTC, cgwalters commented
> I will use another PR to improve this with a clean up process.

Yep, SGTM!

2023-04-11 03:16 UTC, merged