bridge: add support to default-vlan-pvid
nmstate/nmstate pull request #2344
Opened 2023-05-15 16:30 UTC by ffmancera

Add support to default-vlan-pvid, currently the nm_dbus part was already done, so it didn't require much work.

Add integration test.

2023-05-15 16:35 UTC, cathay4t submitted a review, later dismissed
LGTM

2023-05-15 16:42 UTC, cathay4t requested changes
Changes required:
 1. the commit message title is wrong, should be `vlan-default-pvid`.
 2. When desire state contains `vlan-default-pvid` without VLAN filtering enabled, we should return ValueError instead of VerificationError.
 3. Got verification error when using `vlan-default-pvid` with VLAN trunk:

```yml
---
interfaces:
  - name: br0
    type: linux-bridge
    state: up
    bridge:
      options:
        vlan-default-pvid: 1000
      ports:
        - name: eth1
          vlan:
            mode: trunk
            trunk-tags:
            - id: 101
            - id-range:
                min: 500
                max: 599
            tag: 100
            enable-native: true
        - name: eth2
          vlan:
            mode: trunk
            trunk-tags:
            - id: 500
```

2023-05-22 10:30 UTC, ffmancera commented
I fixed the problems you mentioned and all the tests must be passing now. Thanks!

2023-05-23 08:57 UTC, cathay4t approved these changes
Just two trivial issue. Please fix it then we can merge it.

2023-05-23 08:57 UTC, cathay4t commented on rust/src/lib/ifaces/linux_bridge.rs
> +            opts.validate_vlan_default_pvid(self)?;
This function also run against current state, there is no need to validate there. Please check `is_desired` also.

2023-05-23 08:57 UTC, cathay4t commented on rust/src/lib/ifaces/linux_bridge.rs
> +                            "Linux bridge {} has vlan-default-pvid different than 1 but VLAN filtering is not enabled.",
This line is too long. Break it like:

```rust
"Linux bridge {} has vlan-default-pvid different \
than 1 but VLAN filtering is not enabled.",
```

2023-05-23 16:44 UTC, merged