connection: set controller to empty if not present
nmstate/nmstate pull request #2520
Opened 2024-01-09 17:48 UTC by ffmancera

NetworkManager is introducing a new alias for "master" which is "controller". Nmstate is taking unknown DBus parameters and sending it back unmodified. NetworkManager is prioritising "master" over "controller" if both are present but on this situation only "controller" is present.

In order to fix this temporarily, set "master" to empty string. This is going to be dropped when using "controller" everywhere.

2024-01-09 17:48 UTC, ffmancera commented
This is related to: https://gitlab.freedesktop.org/NetworkManager/NetworkManager/-/merge_requests/1809

2024-01-09 18:34 UTC, thom311 commented
> In order to fix this temporarily, set "master" to empty string.

This comment seems not correct? I think the patch does not set master to an empty string.

2024-01-10 07:56 UTC, cathay4t commented
In thread of removing the `controller` property, can we just override it with current `master` value.

2024-01-10 10:18 UTC, ffmancera commented
> In thread of removing the `controller` property, can we just override it with current `master` value.

That would be also fine!

2024-01-10 10:18 UTC, ffmancera commented
> > In order to fix this temporarily, set "master" to empty string.
> 
> This comment seems not correct? I think the patch does not set master to an empty string.

I updated the commit but the PR description didn't change, sorry. Changing it now.

2024-01-15 04:20 UTC, cathay4t requested changes
Instead of removing `controller` as workaround. I prefer we do:
 * If existing NmConnection has `controller` property, use that and discard `master` property.
 * For new NmConnection, we check `nm_api.version()` and use `controller` when possible.

With this, we do not need to visit this topic again in the future.

2024-01-15 10:49 UTC, ihuguet commented
Gris is right.
- If the daemon sends "controller", we know that the daemon is new enough to understand "controller":
    1. If there is also a "master" property, we delete it.
    2. We only send back "controller".
- If the daemon does NOT send "controller":
    - It might be an old daemon: we have to send "master" back.
    - Or it is a transition version that understands "controller" but is still only serializing "master": it will accept either "master" or "controller".
    - Only checking the NM version we can know what case it is, but I don't see the benefit of that. We still have to send "master" for old versions, so let's just send "master" in both cases.

We'll remove the support for "master" when enough time has passed to support only NM >= 1.46.

2024-01-15 23:47 UTC, liangwen12year commented
> Instead of removing `controller` as workaround. I prefer we do:
> 
> * If existing NmConnection has `controller` property, use that and discard `master` property.
> * Optionally: For new NmConnection, we check `nm_api.version()` and use `controller` when possible.
> 
> With this, we do not need to visit this topic again in the future.

+1

2024-01-29 08:28 UTC, ffmancera commented
I am going to work on this also for all the deprecated properties not only "controller".

2024-02-15 15:03 UTC, closed without merging