ip: Support assigning static routes to interface without addresses
nmstate/nmstate pull request #2535
Opened 2024-01-24 22:25 UTC by liangwen12year

OpenShift MetalLB team requests to configure additional routes whenever the nodes does not have a configured IP address or route for the subnet in which MetalLB issues addresses.

Note in linux network stack, it does not matter what interface you add the address on a node (for example, loopback), the kernel is always processing arp-requests and sending arp-replies to any of them, this behavior is considered correct and, moreover, it is widely used in the a dynamic environment as Kubernetes.

https://issues.redhat.com/browse/RHEL-4908

2024-01-24 22:27 UTC, liangwen12year commented
Since the corresponding NM updates landed in NM version 1.45.11, I have manually tested the patch in the container, it works as expected.

2024-01-29 00:09 UTC, liangwen12year commented
Hi @cathay4t , I would like to hear your opinion about two solutions around my implementation on assigning IPv4 static route to interface without ip:
1. when ipv4/6 is enabled, just preserve all the routes on that device by default, when ipv4/6 is disabled, just clear all the routes on that device by default
 2. introduce `allow_routes_on_default` flag to the ipv4/6 setting which is false by default, but this can allow users to explicitly control if they want to preserve the  routes  on that device
 
 Which method is better in your opinion ?

2024-02-01 01:45 UTC, cathay4t requested changes
Please remove the comment regarding treating empty IP address as disabled in `test_remove_all_ip_address` test case.

Besides that, the patch looks good to me.

2024-02-01 05:35 UTC, qinqon approved these changes
lgtm

2024-02-01 13:55 UTC, liangwen12year commented
> Please remove the comment regarding treating empty IP address as disabled in `test_remove_all_ip_address` test case.
> 
> Besides that, the patch looks good to me.

I removed it, thanks.

2024-02-02 12:47 UTC, merged