(Fix)Deprecate PrettyState in python API
nmstate/nmstate pull request #2591
Opened 2024-03-08 08:27 UTC by jona42-ui

Issue: https://github.com/nmstate/nmstate/issues/2588

Description;

The PrettyState is only used for test codes.

    - [x] Mark PrettyState as deprecated in Python API, providing message indicate libnmstate.show() output is already sorted.
    
    - [x]  Remove test cases regarding PrettyState

2024-03-08 08:47 UTC, ffmancera requested changes
There is also a missing place where `PrettyState` needs to be dropped. `tests/integration/ovs_test.py`

2024-03-08 08:47 UTC, ffmancera commented on rust/src/python/libnmstate/prettystate.py
> +
Instead of introducing the warning here, could you place it under the `__init__()` function in `PrettyState` class definition? This way the warning will be displayed when creating an instance of the class.

2024-03-08 08:47 UTC, ffmancera commented on tests/integration/linux_bridge_test.py
> +        assert VLAN_FILTER_PORT_YAML in pretty_state
The whole test case needs to be droppped. The test is specific to pretty_state that we do not want to test anymore. Please drop the whole `test_pretty_state_port_name_first` test.

2024-03-08 09:25 UTC, ffmancera commented
Hi! Instead of creating multiple commits could you unify all the changes into a single one? In addition, instead of doing merges to update the branch, please do rebases. The git history will be more clear

2024-03-08 10:00 UTC, jona42-ui commented
cleaning this up, sorry!

2024-03-08 10:39 UTC, ffmancera commented
It looks much better but the commit message it reflects messages from other commits. I guess this is because you squashed the commits. Please, adjust the commit message to reflect only the relevant information of this task :)

2024-03-08 10:49 UTC, jona42-ui commented
updated, thanks

2024-03-08 11:22 UTC, ffmancera approved these changes

2024-03-08 11:23 UTC, ffmancera commented
LGTM! Let's wait for CI results before merging it

2024-03-08 11:24 UTC, ffmancera commented
Whoops, the linter is failing. Could you follow the formatting suggestion? https://github.com/nmstate/nmstate/actions/runs/8202211120/job/22432495995?pr=2591#step:3:436

```
 class PrettyState:
     def __init__(self, state):
         yaml.add_representer(dict, represent_dict)
-        warnings.warn("The PrettyState class is deprecated and will be removed in a future release. "
-                      "The output of libnmstate.show() is already sorted.", DeprecationWarning)
+        warnings.warn(
+            "The PrettyState class is deprecated and will be removed in a future release. "
+            "The output of libnmstate.show() is already sorted.",
+            DeprecationWarning,
+        )
         self.state = _sort_with_priority(state)
```

2024-03-08 12:41 UTC, jona42-ui commented
the linter is quite annoying!

2024-03-08 13:36 UTC, ffmancera commented
> the linter is quite annoying!

It might be but it is important to take care of the style used when coding. An unified and clean style leads to a codebase easier to read and understand.

There is one more lint error, you are almost there!

```
 +
 class PrettyState:
     def __init__(self, state):
         yaml.add_representer(dict, represent_dict)
         warnings.warn(
             "The PrettyState class is deprecated and will be removed in a future release. "
```

2024-03-08 17:07 UTC, ffmancera commented
All good, merging!

2024-03-08 17:07 UTC, merged

2024-03-13 03:06 UTC, cathay4t commented
According to https://peps.python.org/pep-0702/  we should use `@warnings.deprecated()`. 

@jona42-ui Can you investigate and fix it in next PR?

2024-03-13 03:12 UTC, jona42-ui commented
thanks makes sense

2024-03-13 03:55 UTC, jona42-ui commented
can i make a followup PR with only the decorator fix?