Update code structure section in CONTRIBUTING.md
nmstate/nmstate pull request #2612
Opened 2024-03-20 02:07 UTC by abigailajohn

This commit refreshes the code structure section of the CONTRIBUTING.md file to represent the project directories' current layout accurately. It includes updated descriptions and paths, ensuring new contributors can easily navigate the project.

Resolves: #2592

2024-03-20 18:24 UTC, liangwen12year commented
https://github.com/nmstate/nmstate/blob/base/CONTRIBUTING.md#write-a-good-commit-message, please make sure that the commit message is wrapped around 72 characters?

2024-03-26 00:06 UTC, cathay4t requested changes

2024-03-26 00:06 UTC, cathay4t commented on CONTRIBUTING.md
> +- cargo build
For compiling the whole project, please use `make` at the top level of  code

2024-03-26 00:06 UTC, cathay4t commented on CONTRIBUTING.md
> +- target/debug/nmstatectl show # To dump the state in json format, use the ‘–json’ flag.
The flag is `--json`

2024-03-26 12:47 UTC, abigailajohn commented
@cathay4t I have made the necessary changes as requested.

2024-03-27 09:29 UTC, cathay4t approved these changes

2024-03-29 01:41 UTC, merged