(feat)Use nispor::NetState::retrieve_with_filter_async
nmstate/nmstate pull request #2622
Opened 2024-03-22 15:03 UTC by jona42-ui

As the first step to providing an async API in nmstate, this commit replaces usages of nispor::NetState::retrieve_with_filter() with nispor::NetState::retrieve_with_filter_async(). This change affects the files route.rs, route_rules.rs, show.rs, net_state.rs, and persist_nic.rs.

This change improves the performance and responsiveness of the application by utilizing asynchronous retrieval of network state data.

Resolves:https://github.com/nmstate/nmstate/issues/2580

2024-03-26 07:26 UTC, ffmancera requested changes

2024-03-26 07:26 UTC, ffmancera commented on rust/src/lib/nispor/route.rs
> -
Why are you dropping this?

2024-03-26 07:26 UTC, ffmancera commented on rust/src/lib/nispor/route.rs
> -    route_entry.cwnd = if cwnd_lock { np_route.cwnd } else { None };
An this?

2024-03-26 07:33 UTC, jona42-ui commented
my bad!
commiting them up stream now

2024-03-26 08:01 UTC, jona42-ui commented
thanks @ffmancera

2024-03-26 08:09 UTC, ihuguet commented
Not sure about what @cathay4t wanted exactly here, but I don't think we want to add a dependency to Tokio.
Also, I don't think that replacing public functions for async version of them is OK because it will break the users of those functions. Probably it's better to add the _async version of those functions, additionally to the synchronous ones.
Anyway, I'm a bit speculating, better to see what @cathay4t says.

2024-03-26 10:22 UTC, cathay4t commented
Adding tokio dependency is fine as nispor already depend on it.

But please place `tokio` dependency to `query_apply` feature only in `lib/Cargo.toml`.

The code in general meet my expectation. Instead of change `pub fn retrieve()` to use `block_on`, try:

```
pub async fn retrieve_async() {
    // hold all old codes with awaits
}

pub fn retrieve() {
    block_on(Self::retrieve_async())
}
```

With this, we can change our `nm` to async also in the future without another `block_on()`.

2024-03-26 15:29 UTC, jona42-ui commented
> Adding tokio dependency is fine as nispor already depend on it.
> 
> But please place `tokio` dependency to `query_apply` feature only in `lib/Cargo.toml`.
> 
> The code in general meet my expectation. Instead of change `pub fn retrieve()` to use `block_on`, try:
> 
> ```rust
> pub async fn retrieve_async() {
>     // hold all old codes with awaits
> }
> 
> pub fn retrieve() {
>     block_on(Self::retrieve_async())
> }
> ```
> 
> With this, we can change our `nm` to async also in the future without another `block_on()`.

@cathay4t  thanks so much
but I kindly have not understood the change requests.

2024-03-27 11:19 UTC, jona42-ui commented
I placed the tokio dpendency in the `lib/Cargo.toml` do you mean I need to put it somewhere else?

2024-03-31 09:28 UTC, jona42-ui commented
@cathay4t  it seems you reccomend  
tokio::runtime::Builder::new_multi_thread()
    .enable_all()
    .build()
    .unwrap()
    .block_on(your_async_func) here
https://developers.redhat.com/articles/2023/10/26/how-consume-and-expose-rust-async-crates#how_to_consume_rust_async_crates

to have more control of the tokio runtime

2024-03-31 09:29 UTC, jona42-ui commented
also thank for the writeup, it has helped me understand stuff well

2024-04-01 14:06 UTC, jona42-ui commented
hi @cathay4t 
can you  take a look now?

2024-04-01 14:08 UTC, jona42-ui commented
does this need unit tests?

2024-04-08 06:28 UTC, jona42-ui commented
hi @cathay4t 
made updates here.
waiting for a review
thanks

2024-04-08 06:29 UTC, jona42-ui commented
although checks are failing, anything am missing?

2024-04-08 06:29 UTC, jona42-ui commented
because it builds well

2024-04-08 08:07 UTC, cathay4t requested changes

2024-04-08 08:07 UTC, cathay4t commented on rust/src/lib/Cargo.toml
> +query_apply = ["dep:nispor", "dep:nix", "dep:zbus", "tokio"]
Please follow other example, use `dep:tokio`

2024-04-08 08:07 UTC, cathay4t commented on rust/src/lib/nispor/route.rs
> +        match task::spawn(async move {
We do not need spawn here

2024-04-08 08:08 UTC, cathay4t commented
You find the CI log explaining the failure.

2024-04-08 09:34 UTC, jona42-ui commented
@cathay4t  how best can i run the clib tests

2024-04-09 05:06 UTC, jona42-ui commented
I have handled the rust-unit fail

the rest seem strange to me especially the ...tier

2024-07-08 09:23 UTC, cathay4t commented
This has been fixed by https://github.com/nmstate/nmstate/pull/2676

2024-07-08 09:23 UTC, closed without merging