Use Workspace Dependencies #2406
nmstate/nmstate pull request #2632
Opened 2024-03-28 08:22 UTC by abigailajohn

This PR updates the workspace to use unified dependency
versions for serde, log, and serde_yaml. The goal is to
leverage common dependencies across all crates,
ensuring consistency and simplifying the dependency.

Changes:
Set serde_yaml, log, and serde in workspace Cargo.toml
Unified log version to 0.4.17
Aligned serde to 1.0.137 with derive feature

Testing:
Ran cargo build successfully with no errors
All tests passed with cargo test

resolves [#2406](https://github.com/nmstate/nmstate/issues/2406)

2024-04-03 11:15 UTC, cathay4t requested changes
Could you move all crate dependency to top workspace level so we have single place for dependencies.

2024-04-03 15:13 UTC, abigailajohn commented
> Could you move all crate dependency to top workspace level so we have single place for dependencies.

could you clarify if by "all crate dependency" you are referring to every single dependency including those used by only one crate, or just the shared dependencies?

2024-04-08 14:03 UTC, cathay4t commented
every crates

2024-04-09 23:30 UTC, cathay4t requested changes
Nix zbus are not found in workspace yet.

2024-04-09 23:30 UTC, cathay4t commented on rust/Cargo.toml
> +nmstate = { path = "src/lib", default-features = false }
Version is missing, it is needed for uploading to crates.io

2024-04-10 03:08 UTC, abigailajohn commented
> Nix zbus are not found in workspace yet.

I have added them to the workspace and also added the nmstate version.

2024-04-11 05:05 UTC, cathay4t requested changes
There are still leftover!

2024-04-12 06:59 UTC, cathay4t approved these changes

2024-04-12 07:19 UTC, merged