automation: install dnf5 copr module for Rawhide
nmstate/nmstate pull request #2711
Opened 2024-06-21 14:47 UTC by vbenes

We need to have dnf5 copr plugin installed in Rawhide as dnf5 is the default there.

2024-06-21 15:47 UTC, cathay4t requested changes

2024-06-21 15:47 UTC, cathay4t commented on automation/run-tests.sh
> +    exec_cmd "command -v dnf && plugin='dnf5-command(copr)' || \
```bash
"command -v dnf5 && plugin='dnf5-command(copr)' || \
"command -v dnf && plugin='dnf-command(copr)'
```

2024-06-24 12:21 UTC, vbenes commented on automation/run-tests.sh
> +    exec_cmd "command -v dnf && plugin='dnf5-command(copr)' || \
done!

2024-06-24 12:24 UTC, vbenes commented
oh oh, some confusion happened here, why oh why was I on the base branch for this PR?

2024-06-24 12:26 UTC, closed without merging