tests: Add the description for dynamic ip integration tests
nmstate/nmstate pull request #2738
Opened 2024-07-12 01:36 UTC by liangwen12year

2024-07-15 16:08 UTC, liangwen12year commented
The following are the generated yaml states: 

- question: Delete the dummy device dummy00
  answer: |
    ---
    interfaces:
    - name: dummy00
      type: dummy
      state: absent
- question: Configure the dummy device dummy00 with IPv4 enabled, dhcp4 enabled, auto dns enabled, auto gateway enabled, auto routes enabled, auto route table ID set to 0. Configure the dummy device dummy00 with IPv6 enabled, dhcp6 enabled, IPv6 autoconf enabled, IPv6 auto dns enabled, IPv6 auto gateway enabled, IPv6 auto routes enabled, IPv6 auto route table id set to 0
  answer: |
    ---
    interfaces:
    - name: dummy00
      type: dummy
      state: up
      ipv4:
        enabled: true
        dhcp: true
        auto-dns: true
        auto-gateway: true
        auto-routes: true
        auto-route-table-id: 0
      ipv6:
        enabled: true
        dhcp: true
        autoconf: true
        auto-dns: true
        auto-gateway: true
        auto-routes: true
        auto-route-table-id: 0
- question: Bring up the dummy device dummy00
  answer: |
    ---
    interfaces:
    - name: dummy00
      type: dummy
      state: up
- question: Bring up the dummy device dummy00
  answer: |
    ---
    interfaces:
    - name: dummy00
      type: dummy
      state: up
- question: Configure the dummy device dummy00 with IPv4 enabled, dhcp4 enabled, auto dns enabled, auto gateway enabled, auto routes enabled, auto route table ID set to 0. Configure the dummy device dummy00 with IPv6 enabled, dhcp6 enabled, IPv6 autoconf enabled, IPv6 auto dns enabled, IPv6 auto gateway enabled, IPv6 auto routes enabled, IPv6 auto route table id set to 0
  answer: |
    ---
    interfaces:
    - name: dummy00
      type: dummy
      state: up
      ipv4:
        enabled: true
        dhcp: true
        auto-dns: true
        auto-gateway: true
        auto-routes: true
        auto-route-table-id: 0
- question: Delete the dummy device dummy00
  answer: |
    ---
    interfaces:
    - name: dummy00
      type: dummy
      state: absent
- question: Delete the dummy device dummy00
  answer: |
    ---
    interfaces:
    - name: dummy00
      type: dummy
      state: absent
- question: Configure the dummy device dummy00 with IPv4 enabled, dhcp4 enabled, auto dns enabled, auto gateway enabled, auto routes enabled, auto route table ID set to 0. Configure the dummy device dummy00 with IPv6 enabled, dhcp6 enabled, IPv6 autoconf enabled, IPv6 auto dns enabled, IPv6 auto gateway enabled, IPv6 auto routes enabled, IPv6 auto route table id set to 0
  answer: |
    ---
    interfaces:
    - name: dummy00
      type: dummy
      state: up
      ipv6:
        enabled: true
        dhcp: true
        autoconf: true
        auto-dns: true
        auto-gateway: true
        auto-routes: true
        auto-route-table-id: 0
- question: Bring up the dummy device dummy00
  answer: |
    ---
    interfaces:
    - name: dummy00
      type: dummy
      state: up
- question: Configure the DNS server to 8.8.8.8. Configure the ethernet device dhcpcli with IPv4 enabled, DHCP4 enabled, IPv4 auto dns set to true, IPv4 auto gateway set to true, IPv4 auto routes enabled, IPv4 auto route table id set to 0. Configure the ethernet interface dhcpcli with IPv6 enabled, DHCP6 enabled, IPv6 autoconf enabled, IPv6 auto dns enabled, IPv6 auto gateway enabled, IPv6 auto routes enabled, IPv6 auto route table id set to 0.
  answer: |
    ---
    dns-resolver:
      config:
        server:
        - 8.8.8.8
    interfaces:
    - name: dhcpcli
      type: ethernet
      state: up
      ipv4:
        enabled: true
        dhcp: true
        auto-dns: true
        auto-gateway: true
        auto-routes: true
        auto-route-table-id: 0
      ipv6:
        enabled: true
        dhcp: true
        autoconf: true
        auto-dns: true
        auto-gateway: true
        auto-routes: true
        auto-route-table-id: 0
- question: Clear the DNS config
  answer: |
    ---
    dns-resolver:
      config: {}
- question: Remove the interface dhcpcli
  answer: |
    ---
    interfaces:
    - name: dhcpcli
      type: ethernet
      state: absent
- question: Configure the dhcpcli ethernet interface with dhcp4 enabled, IPv4 auto-dns enabled, IPv4 auto-gateway enabled, IPv4 auto-routes enabled, IPv4 auto route table id set to 0. Configure the dhcpcli ethernet interface with dhcp6 enabled, IPv6 autoconf enabled, IPv6 auto-dns enabled, IPv6 auto-gateway enabled, IPv6 auto-routes enabled, IPv6 auto route table id set to 0.
  answer: |
    ---
    interfaces:
    - name: dhcpcli
      type: ethernet
      state: up
      ipv4:
        enabled: true
        dhcp: true
        auto-dns: true
        auto-gateway: true
        auto-routes: true
        auto-route-table-id: 0
      ipv6:
        enabled: true
        dhcp: true
        autoconf: true
        auto-dns: true
        auto-gateway: true
        auto-routes: true
        auto-route-table-id: 0
- question: Configure the ethernet device dhcpcli with the IPv6 address generation mode stable-privacy configured
  answer: |
    ---
    interfaces:
    - name: dhcpcli
      type: ethernet
      state: up
      ipv6:
        addr-gen-mode: stable-privacy
- question: Configure the dhcpcli ethernet interface with dhcp4 enabled, IPv4 auto-dns enabled, IPv4 auto-gateway enabled, IPv4 auto-routes enabled, IPv4 auto route table id set to 0. Configure the dhcpcli ethernet interface with dhcp6 enabled, IPv6 autoconf enabled, IPv6 auto-dns enabled, IPv6 auto-gateway enabled, IPv6 auto-routes enabled, IPv6 auto route table id set to 0.
  answer: |
    ---
    interfaces:
    - name: dhcpcli
      type: ethernet
      state: up
      ipv4:
        enabled: true
        dhcp: true
        auto-dns: true
        auto-gateway: true
        auto-routes: true
        auto-route-table-id: 0
      ipv6:
        enabled: true
        dhcp: true
        autoconf: true
        auto-dns: true
        auto-gateway: true
        auto-routes: true
        auto-route-table-id: 0
- question: Remove the interface dhcpcli
  answer: |
    ---
    interfaces:
    - name: dhcpcli
      type: ethernet
      state: absent
- question: Configure the next hop device dhcpcli with the route destination 2001:db8:2::/64 and next hop address 2001:db8:1::1, configure the next hop interface dhcpcli with the route destination 203.0.113.0/24 and next hop address 192.0.2.251. Configure the ethernet device dhcpcli with IPv4 enabled, DHCP4 set to True, IPv4 auto dns set to true, IPv4 auto gateway set to true, IPv4 auto routes enabled, IPv4 auto route table id set to 0.Configure the ethernet interface dhcpcli with IPv6 enabled, DHCP6 enabled, IPv6 autoconf enabled, IPv6 auto dns enabled, IPv6 auto gateway enabled, IPv6 auto routes enabled, IPv6 auto route table id set to 0.
    routes:
      config:
      - destination: 2001:db8:2::/64
        next-hop-interface: dhcpcli
        next-hop-address: 2001:db8:1::1
      - destination: 203.0.113.0/24
        next-hop-interface: dhcpcli
        next-hop-address: 192.0.2.251
  answer: |
    ---
    interfaces:
    - name: dhcpcli
      type: ethernet
      state: up
      ipv4:
        enabled: true
        dhcp: true
        auto-dns: true
        auto-gateway: true
        auto-routes: true
        auto-route-table-id: 0
      ipv6:
        enabled: true
        dhcp: true
        autoconf: true
        auto-dns: true
        auto-gateway: true
        auto-routes: true
        auto-route-table-id: 0
- question: Configure the ethernet device eth1 with IPv4 enabled, DHCP4 set to True, IPv4 auto dns set to true, IPv4 auto gateway set to true, IPv4 auto routes enabled, IPv4 auto route table id set to 0.Configure the ethernet interface eth1 with IPv6 enabled, DHCP6 enabled, IPv6 autoconf enabled, IPv6 auto dns enabled, IPv6 auto gateway enabled, IPv6 auto routes enabled, IPv6 auto route table id set to 0.
  answer: |
    ---
    interfaces:
    - name: eth1
      type: ethernet
      state: up
      ipv4:
       [...]

2024-07-21 23:30 UTC, liangwen12year commented
The following are the generated yaml states: (The description is replaced with question to fit the training code):

```
description: Configure the dummy device dummy00 with dhcp4 and dhcp6 enabled
interfaces:
- name: dummy00
  type: dummy
  state: up
  ipv4:
    enabled: true
    dhcp: true
    auto-dns: true
    auto-gateway: true
    auto-routes: true
    auto-route-table-id: 0
  ipv6:
    enabled: true
    dhcp: true
    autoconf: true
    auto-dns: true
    auto-gateway: true
    auto-routes: true
    auto-route-table-id: 0
description: Bring up the dummy device dummy00
interfaces:
- name: dummy00
  type: dummy
  state: up
description: Delete the dummy device dummy00
interfaces:
- name: dummy00
  type: dummy
  state: absent
description: Delete the dummy device dummy00
interfaces:
- name: dummy00
  type: dummy
  state: absent
description: Bring up the dummy device dummy00
interfaces:
- name: dummy00
  type: dummy
  state: up
description: Configure the dummy device dummy00 with dhcp4 and dhcp6 enabled
interfaces:
- name: dummy00
  type: dummy
  state: up
  ipv4:
    enabled: true
    dhcp: true
    auto-dns: true
    auto-gateway: true
    auto-routes: true
    auto-route-table-id: 0
description: Delete the dummy device dummy00
interfaces:
- name: dummy00
  type: dummy
  state: absent
description: Configure the dummy device dummy00 with dhcp4 and dhcp6 enabled
interfaces:
- name: dummy00
  type: dummy
  state: up
  ipv6:
    enabled: true
    dhcp: true
    autoconf: true
    auto-dns: true
    auto-gateway: true
    auto-routes: true
    auto-route-table-id: 0
description: Bring up the dummy device dummy00
interfaces:
- name: dummy00
  type: dummy
  state: up
description: Clear the DNS config
dns-resolver:
  config: {}
interfaces: []
description: Configure the DNS server to 8.8.8.8. Configure the ethernet device dhcpcli with DHCP4 enabled and DHCP6 enabled
dns-resolver:
  config:
    server:
    - 8.8.8.8
interfaces:
- name: dhcpcli
  type: ethernet
  state: up
  ipv4:
    enabled: true
    dhcp: true
    auto-dns: true
    auto-gateway: true
    auto-routes: true
    auto-route-table-id: 0
  ipv6:
    enabled: true
    dhcp: true
    autoconf: true
    auto-dns: true
    auto-gateway: true
    auto-routes: true
    auto-route-table-id: 0
description: Configure the dhcpcli ethernet interface with dhcp4 and dhcp6 enabled
interfaces:
- name: dhcpcli
  type: ethernet
  state: up
  ipv4:
    enabled: true
    dhcp: true
    auto-dns: true
    auto-gateway: true
    auto-routes: true
    auto-route-table-id: 0
  ipv6:
    enabled: true
    dhcp: true
    autoconf: true
    auto-dns: true
    auto-gateway: true
    auto-routes: true
    auto-route-table-id: 0
description: Remove the interface dhcpcli
interfaces:
- name: dhcpcli
  type: ethernet
  state: absent
description: Configure the ethernet device dhcpcli with the IPv6 address generation mode stable-privacy
interfaces:
- name: dhcpcli
  type: ethernet
  state: up
  ipv6:
    addr-gen-mode: stable-privacy
description: Configure the dhcpcli ethernet interface with dhcp4 and dhcp6 enabled
interfaces:
- name: dhcpcli
  type: ethernet
  state: up
  ipv4:
    enabled: true
    dhcp: true
    auto-dns: true
    auto-gateway: true
    auto-routes: true
    auto-route-table-id: 0
  ipv6:
    enabled: true
    dhcp: true
    autoconf: true
    auto-dns: true
    auto-gateway: true
    auto-routes: true
    auto-route-table-id: 0
description: Remove the interface dhcpcli
interfaces:
- name: dhcpcli
  type: ethernet
  state: absent
description: Configure the destination route 2001:db8:2::/64 to the next hop address 2001:db8:1::1 and the destination route 203.0.113.0/24 to the next hop address 192.0.2.251 on the device dhcpcli. Enable the dhcp4 and dhcp6 on the device dhcpcli
routes:
  config:
  - destination: 2001:db8:2::/64
    next-hop-interface: dhcpcli
    next-hop-address: 2001:db8:1::1
  - destination: 203.0.113.0/24
    next-hop-interface: dhcpcli
    next-hop-address: 192.0.2.251
interfaces:
- name: dhcpcli
  type: ethernet
  state: up
  ipv4:
    enabled: true
    dhcp: true
    auto-dns: true
    auto-gateway: true
    auto-routes: true
    auto-route-table-id: 0
  ipv6:
    enabled: true
    dhcp: true
    autoconf: true
    auto-dns: true
    auto-gateway: true
    auto-routes: true
    auto-route-table-id: 0
description: Configure the ethernet device eth1 with DHCP4 and DHCP6 enabled
interfaces:
- name: eth1
  type: ethernet
  state: up
  ipv4:
    enabled: true
    dhcp: true
    address: []
    auto-dns: true
    auto-gateway: true
    auto-routes: true
    auto-route-table-id: 0
  ipv6:
    enabled: true
    dhcp: true
    autoconf: true
    address: []
    auto-dns: true
    auto-gateway: true
    auto-routes: true
    auto-route-table-id: 0
description: Configure the dhcpcli ethernet interface with dhcp4 and dhcp6 enabled
interfaces:
- name: dhcpcli
  type: ethernet
  state: up
  ipv4:
    enabled: true
    dhcp: true
    auto-dns: true
    auto-gateway: true
    auto-routes: true
    auto-route-table-id: 0
  ipv6:
    enabled: true
    dhcp: true
    autoconf: true
    auto-dns: true
    auto-gateway: true
    auto-routes: true
    auto-route-table-id: 0
description: Remove the interface dhcpcli
interfaces:
- name: dhcpcli
  type: ethernet
  state: absent
description: Configure the ethernet device dhcpcli with IPv4 auto-route-metric 901 and IPv6 auto-route-metric 902 configured
interfaces:
- name: dhcpcli
  type: ethernet
  state: up
  ipv4:
    auto-route-metric: 901
  ipv6:
    auto-route-metric: 902
description: Configure the ethernet device dhcpcli with the IPv6 token ::fad
interfaces:
- name: dhcpcli
  type: ethernet
  state: up
  ipv6:
    token: ::fad
description: Enable dhcp6 and autoconf on the ethernet device dhcpcli with IPv6 token ::fac specified
interfaces:
- name: dhcpcli
  type: ethernet
  state: up
  ipv6:
    enabled: true
    dhcp: true
    autoconf: true
    auto-dns: true
    auto-gateway: true
    auto-routes: true
    token: ::fac
description: Configure the ethernet interface dhcpcli with IPv4 address 192.0.2.252/24 and IPv6 address 2001:db8:2::1/64
interfaces:
- name: dhcpcli
  type: ethernet
  state: up
  ipv4:
    enabled: true
    dhcp: false
    address:
    - ip: 192.0.2.252
      prefix-length: 24
  ipv6:
    enabled: true
    dhcp: false
    autoconf: false
    address:
    - ip: 2001:db8:2::1
      prefix-length: 64
description: Enable DHCP4 but disabled IPv6 on the ethernet device dhcpcli
interfaces:
- name: dhcpcli
  type: ethernet
  state: up
  ipv4:
    dhcp: true
    auto-dns: true
    auto-gateway: true
    auto-routes: true
    auto-route-table-id: 0
  ipv6:
    enabled: false
description: Configure the ethernet interface dhcpcli with IPv4 address 192.0.2.252/24 and IPv6 address 2001:db8:2::1/64
interfaces:
- name: dhcpcli
  type: ethernet
  state: up
  ipv4:
    enabled: true
    dhcp: false
    address:
    - ip: 192.0.2.252
      prefix-length: 24
  ipv6:
    enabled: true
    dhcp: false
    autoconf: false
    address:
    - ip: 2001:db8:2::1
      prefix-length: 64
description: Configure the etheret device dhcpcli with IPv4 disabled, IPv6 autoconf enabled
interfaces:
- name: dhcpcli
  type: ethernet
  state: up
  ipv4:
    enabled: false
  ipv6:
    dhcp: true
    autoconf: true
    auto-dns: true
    auto-gateway: true
    auto-routes: true
    auto-route-table-id: 0
description: Enable dhcp6 and autoconf on the ethernet device dhcpcli with IPv6 token ::fac specified
interfaces:
- name: dhcpcli
  type: ethernet
  state: up
  ipv6:
    enabled: true
    dhcp: true
    autoconf: true
    auto-dns: true
    auto-gateway: true
    auto-routes: true
    token: ::fac
description: Configure the ethernet device dhcpcli with DHCP4 enabled. Configure the ethernet device dhcpcli with IPv6 address 2001:db8:2::1/64 configured
interfaces:
- name: dhcpcli
  type: ethernet
  state: up
  ipv4:
    enabled: true
    dhcp: true
    auto-dns: true
    auto-gateway: [...]

2024-11-04 07:16 UTC, cathay4t requested changes
Besides other comments, please change `DHCP4` or `DHCP6` to `DHCPv4` and `DHCPv6` as RFC did.

2024-11-04 07:16 UTC, cathay4t commented on tests/integration/dynamic_ip_test.yaml
> +description: Configure the dummy device dummy00 with DHCP4, IPv4 auto dns, IPv4 auto gateway, IPv4 auto routes, IPv4 auto route table ID 0, DHCP6, autoconf, IPv6 auto dns, IPv6 auto gateway, IPv6 aut
`auto route table ID 0` -> `use default auto route table ID`.

2024-11-04 07:16 UTC, cathay4t commented on tests/integration/dynamic_ip_test.yaml
> +description: Configure the ethernet device eth1 with DHCP4, IPv4 auto dns, IPv4 auto gateway, IPv4 auto routes, IPv4 auto route table ID 0, DHCP6, autoconf, IPv6 auto dns, IPv6 auto gateway, IPv6 aut
You missed `address: []` means `no static IP address`.

2024-11-04 07:16 UTC, cathay4t commented on tests/integration/dynamic_ip_test.yaml
> +description: Configure the ethernet interface dhcpcli with address 192.0.2.252/24 and 2001:db8:2::1/64
with static IP

2024-11-04 07:16 UTC, cathay4t commented on tests/integration/dynamic_ip_test.yaml
> +description: Configure the ethernet device dhcpcli to have IPv6 dhcp-duid 0f:66:55:BC:73:4D configured
`Configure ... configured` seems not a good sentence to me. 

`Configure the ethernet device dhcpcli with IPv6 dhcp-duid 0f:66:55:BC:73:4D`

2024-11-04 07:16 UTC, cathay4t commented on tests/integration/dynamic_ip_test.yaml
> +description: Do not apply DNS resolver information and the routes retrieved from DHCP4 on the ethernet device eth0. Do not apply DNS resolver information and the routes retrieved from autoconf
`from autoconf or DHCPv6`

2024-11-04 07:16 UTC, cathay4t commented on tests/integration/dynamic_ip_test.yaml
> +description: Do not apply DNS resolver information and the routes retrieved from DHCP4 on the ethernet device eth0. Do not apply DNS resolver information and the routes retrieved from autoconf
DHCPv6 can still provide DNS resolver information.

2024-11-04 07:16 UTC, cathay4t commented on tests/integration/dynamic_ip_test.yaml
> +description: Configure the DNS server to 10.11.5.19 and 10.2.32.1, configure the ethernet device dhcpcli to have the IPv4 and IPv6 disabled. Configure the ethernet device eth0 to apply DNS resolver i
`Set the static DNS nameservers to 10.11.5.19 and 10.2.32.1 and empty search domains`.

2024-11-04 07:16 UTC, cathay4t commented on tests/integration/dynamic_ip_test.yaml
> +description: Configure the DNS server to 2001:4860:4860::8888 and 8.8.8.8, configure the dns search to example.org and example.com. Configure the ethernet device dhcpcli with DHCP4 and IPv4 auto dns
No sure why you always start a description with `configure`, but I never do that if I want to change network settings.

Try: `Change ...`, `Set ...`

2024-11-04 07:17 UTC, cathay4t commented on tests/integration/dynamic_ip_test.yaml
> +description: Configure the ethernet device dhcpcli, set the address 192.0.2.252/24
Configure the ethernet device dhcpcli with static ip 192.0.2.252/24 and DHCPv4 disabled.

2024-11-04 19:22 UTC, liangwen12year commented
@cathay4t , I addressed all your comments, thanks.

2024-11-12 12:12 UTC, cathay4t approved these changes

2024-11-12 12:41 UTC, liangwen12year commented
```
description: Delete the dummy device dummy00
interfaces:
- name: dummy00
  type: dummy
  state: absent
description: Configure the dummy device dummy00 with DHCPv4, IPv4 auto dns, IPv4 auto gateway, IPv4 auto routes, use default auto route table ID for IPv4, DHCPv6, autoconf, IPv6 auto dns, IPv6 auto gateway, IPv6 auto routes, use default auto route table ID for IPv6
interfaces:
- name: dummy00
  type: dummy
  state: up
  ipv4:
    enabled: true
    dhcp: true
    auto-dns: true
    auto-gateway: true
    auto-routes: true
    auto-route-table-id: 0
  ipv6:
    enabled: true
    dhcp: true
    autoconf: true
    auto-dns: true
    auto-gateway: true
    auto-routes: true
    auto-route-table-id: 0
description: Bring up the dummy device dummy00
interfaces:
- name: dummy00
  type: dummy
  state: up
description: Bring up the dummy device dummy00
interfaces:
- name: dummy00
  type: dummy
  state: up
description: Configure the dummy device dummy00 with DHCPv4, IPv4 auto dns, IPv4 auto gateway, IPv4 auto routes, use default auto route table ID for IPv4, DHCPv6, autoconf, IPv6 auto dns, IPv6 auto gateway, IPv6 auto routes, use default auto route table ID for IPv6
interfaces:
- name: dummy00
  type: dummy
  state: up
  ipv4:
    enabled: true
    dhcp: true
    auto-dns: true
    auto-gateway: true
    auto-routes: true
    auto-route-table-id: 0
description: Delete the dummy device dummy00
interfaces:
- name: dummy00
  type: dummy
  state: absent
description: Delete the dummy device dummy00
interfaces:
- name: dummy00
  type: dummy
  state: absent
description: Configure the dummy device dummy00 with DHCPv4, IPv4 auto dns, IPv4 auto gateway, IPv4 auto routes, use default auto route table ID for IPv4, DHCPv6, autoconf, IPv6 auto dns, IPv6 auto gateway, IPv6 auto routes, use default auto route table ID for IPv6
interfaces:
- name: dummy00
  type: dummy
  state: up
  ipv6:
    enabled: true
    dhcp: true
    autoconf: true
    auto-dns: true
    auto-gateway: true
    auto-routes: true
    auto-route-table-id: 0
description: Bring up the dummy device dummy00
interfaces:
- name: dummy00
  type: dummy
  state: up
description: Configure the DNS server to 8.8.8.8. Configure the ethernet device dhcpcli with DHCPv4, IPv4 auto dns, IPv4 auto gateway, IPv4 auto routes, use default auto route table ID for IPv4, DHCPv6, autoconf, IPv6 auto dns, IPv6 auto gateway, IPv6 auto routes, use default auto route table ID for IPv6
dns-resolver:
  config:
    server:
    - 8.8.8.8
interfaces:
- name: dhcpcli
  type: ethernet
  state: up
  ipv4:
    enabled: true
    dhcp: true
    auto-dns: true
    auto-gateway: true
    auto-routes: true
    auto-route-table-id: 0
  ipv6:
    enabled: true
    dhcp: true
    autoconf: true
    auto-dns: true
    auto-gateway: true
    auto-routes: true
    auto-route-table-id: 0
description: Clear the DNS config
dns-resolver:
  config: {}
interfaces: []
description: Remove the interface dhcpcli
interfaces:
- name: dhcpcli
  type: ethernet
  state: absent
description: Configure the dhcpcli ethernet interface with DHCPv4, IPv4 auto dns, IPv4 auto gateway, IPv4 auto routes, IPv4 auto route table ID 0, DHCPv6, autoconf, IPv6 auto dns, IPv6 auto gateway, IPv6 auto routes, use default auto route table ID for IPv6
interfaces:
- name: dhcpcli
  type: ethernet
  state: up
  ipv4:
    enabled: true
    dhcp: true
    auto-dns: true
    auto-gateway: true
    auto-routes: true
    auto-route-table-id: 0
  ipv6:
    enabled: true
    dhcp: true
    autoconf: true
    auto-dns: true
    auto-gateway: true
    auto-routes: true
    auto-route-table-id: 0
description: Remove the interface dhcpcli
interfaces:
- name: dhcpcli
  type: ethernet
  state: absent
description: Configure the dhcpcli ethernet interface with DHCPv4, IPv4 auto dns, IPv4 auto gateway, IPv4 auto routes, IPv4 auto route table ID 0, DHCPv6, autoconf, IPv6 auto dns, IPv6 auto gateway, IPv6 auto routes, use default auto route table ID for IPv6
interfaces:
- name: dhcpcli
  type: ethernet
  state: up
  ipv4:
    enabled: true
    dhcp: true
    auto-dns: true
    auto-gateway: true
    auto-routes: true
    auto-route-table-id: 0
  ipv6:
    enabled: true
    dhcp: true
    autoconf: true
    auto-dns: true
    auto-gateway: true
    auto-routes: true
    auto-route-table-id: 0
description: Configure the ethernet device dhcpcli with the IPv6 address generation mode stable-privacy
interfaces:
- name: dhcpcli
  type: ethernet
  state: up
  ipv6:
    addr-gen-mode: stable-privacy
description: Configure the destination route 2001:db8:2::/64 to the next hop address 2001:db8:1::1 and the destination route 203.0.113.0/24 to the next hop address 192.0.2.251 on the device dhcpcli. Configure the dhcpcli ethernet interface with DHCPv4, IPv4 auto dns, IPv4 auto gateway, IPv4 auto routes, use default auto route table ID for IPv4, DHCPv6, autoconf, IPv6 auto dns, IPv6 auto gateway, IPv6 auto routes, use default auto route table ID for IPv6
routes:
  config:
  - destination: 2001:db8:2::/64
    next-hop-interface: dhcpcli
    next-hop-address: 2001:db8:1::1
  - destination: 203.0.113.0/24
    next-hop-interface: dhcpcli
    next-hop-address: 192.0.2.251
interfaces:
- name: dhcpcli
  type: ethernet
  state: up
  ipv4:
    enabled: true
    dhcp: true
    auto-dns: true
    auto-gateway: true
    auto-routes: true
    auto-route-table-id: 0
  ipv6:
    enabled: true
    dhcp: true
    autoconf: true
    auto-dns: true
    auto-gateway: true
    auto-routes: true
    auto-route-table-id: 0
description: Configure the ethernet device eth1 with DHCPv4, no static IPv4 address, IPv4 auto dns, IPv4 auto gateway, IPv4 auto routes, use default auto route table ID for IPv4, DHCPv6, no static IPv6 address, autoconf, IPv6 auto dns, IPv6 auto gateway, IPv6 auto routes, use default auto route table ID for IPv6
interfaces:
- name: eth1
  type: ethernet
  state: up
  ipv4:
    enabled: true
    dhcp: true
    address: []
    auto-dns: true
    auto-gateway: true
    auto-routes: true
    auto-route-table-id: 0
  ipv6:
    enabled: true
    dhcp: true
    autoconf: true
    address: []
    auto-dns: true
    auto-gateway: true
    auto-routes: true
    auto-route-table-id: 0
description: Configure the ethernet device dhcpcli with IPv4 auto-route-metric 901 and IPv6 auto-route-metric 902 configured
interfaces:
- name: dhcpcli
  type: ethernet
  state: up
  ipv4:
    auto-route-metric: 901
  ipv6:
    auto-route-metric: 902
description: Remove the interface dhcpcli
interfaces:
- name: dhcpcli
  type: ethernet
  state: absent
description: Configure the dhcpcli ethernet interface with DHCPv4, IPv4 auto dns, IPv4 auto gateway, IPv4 auto routes, IPv4 auto route table ID 0, DHCPv6, autoconf, IPv6 auto dns, IPv6 auto gateway, IPv6 auto routes, use default auto route table ID for IPv6
interfaces:
- name: dhcpcli
  type: ethernet
  state: up
  ipv4:
    enabled: true
    dhcp: true
    auto-dns: true
    auto-gateway: true
    auto-routes: true
    auto-route-table-id: 0
  ipv6:
    enabled: true
    dhcp: true
    autoconf: true
    auto-dns: true
    auto-gateway: true
    auto-routes: true
    auto-route-table-id: 0
description: Configure the ethernet device dhcpcli with the IPv6 token ::fad
interfaces:
- name: dhcpcli
  type: ethernet
  state: up
  ipv6:
    token: ::fad
description: Configure the ethernet interface dhcpcli with DHCPv6, autoconf, IPv6 auto dns, IPv6 auto gateway, IPv6 auto routes, and IPv6 token ::fac specified
interfaces:
- name: dhcpcli
  type: ethernet
  state: up
  ipv6:
    enabled: true
    dhcp: true
    autoconf: true
    auto-dns: true
    auto-gateway: true
    auto-routes: true
    token: ::fac
description: Configure the ethernet interface dhcpcli with static IP address 192.0.2.252/24 and 2001:db8:2::1/64
interfaces:
- name: dhcpcli
  type: ethernet
  state: up
  ipv4:
    enabled: true
    dhcp: false
    address:
    - ip: 192.0.2.252
      prefix-length: 24
  ipv6:
    enabled: true
    dhcp: false
 [...]

2024-11-12 13:08 UTC, merged