route: Add support for route source
nmstate/nmstate pull request #2770
Opened 2024-08-30 03:20 UTC by liangwen12year

2024-08-30 14:54 UTC, liangwen12year commented
@cathay4t , the test failure `test_iface_down_with_routes_in_current` is transient, I ran the test `test_iface_down_with_routes_in_current` 50 times locally, but I can not reproduce the issue.

2024-08-31 15:35 UTC, cathay4t requested changes
If we are using `source: Option<String>` instead of `Option<IpAddr>` for unknown future, we need to do sanitize for it in case user ask for `source: 2001:0db8:85a3:0000:0000:8a2e:0370:7331`.

2024-09-03 00:28 UTC, liangwen12year commented
> If we are using `source: Option<String>` instead of `Option<IpAddr>` for unknown future, we need to do sanitize for it in case user ask for `source: 2001:0db8:85a3:0000:0000:8a2e:0370:7331`.

I think that I already added the sanitize code, as you can see, 
```
        if let Some(src) = self.source.as_ref() {
            let new_src = format!("{}", src.parse::<std::net::IpAddr>()?);
            if src != &new_src {
                log::warn!(
                    "Route source address {} sanitized to {}",
                    src,
                    new_src
                );
                self.source = Some(new_src);
            }
        }
```
And I tested the sanitize function, as you can see, the src is indeed sanitized
```
[2024-09-03T00:24:28Z WARN  nmstate::route] Route source address 2001:0db8:85a3:0000:0000:8a2e:0370:7001 sanitized to 2001:db8:85a3::8a2e:370:7001
route-rules: {}
routes:
  config:
  - destination: 2003:db8:85a3::8a2e:370:7020/128
    next-hop-interface: eth1
    next-hop-address: 2001:db8:85a3::8a2e:370:1
    metric: 150
    table-id: 254
    source: 2001:db8:85a3::8a2e:370:7001
interfaces: []
ovn: {}
```

2024-09-10 02:01 UTC, cathay4t commented
Please create  a unit test case for this sanitize instead of `I tested`

2024-09-10 02:05 UTC, cathay4t requested changes

2024-09-10 02:05 UTC, cathay4t commented on rust/src/lib/route.rs
> +            let new_src = format!("{}", src.parse::<std::net::IpAddr>()?);
Instead of trust auto error converter, I think it is better to `map_err` providing better error message.

2024-09-10 02:05 UTC, cathay4t commented on rust/src/lib/route.rs
> +                    "Route source address {} sanitized to {}",
It is not a warning, the uncompressed IPv6 address is still legal. Use `log::info`.

2024-09-10 02:05 UTC, cathay4t commented on tests/integration/route_test.py
> +def test_add_static_route_with_route_src(eth1_up):
Need test case for IPv6 route src also.

2024-09-10 04:07 UTC, liangwen12year commented
> Please create a unit test case for this sanitize instead of `I tested`

I created the unit test case.

2024-09-10 12:18 UTC, liangwen12year commented
@cathay4t , all your comments are resolved, thanks !

2024-09-12 01:47 UTC, cathay4t approved these changes

2024-09-12 01:47 UTC, merged